// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://haeslzdjkaddqjnnwbos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhZXNsemRqa2FkZHFqbm53Ym9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MDMxODcsImV4cCI6MjA2ODE3OTE4N30.TdRvAecB-vY5v8lEpiluBARgeCnmGEyEwu4zcmahtFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});